name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-shanghai.aliyuncs.com
        username: "${{ secrets. DOCKER_USERNAME }}"
        password: "${{ secrets. DOCKER_PASSWORD }}"
        egion-id: cn-shanghai
    - name: Build and push image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t registry.cn-shanghai.aliyuncs.com/store-admin/xs-web-admin:$IMAGE_TAG .
        docker push registry.cn-shanghai.aliyuncs.com/store-admin/xs-web-admin:$IMAGE_TAG
