name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
        registry: registry.cn-shanghai.aliyuncs.com
    # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.cn-shanghai.aliyuncs.com/store_admin/xs-web-admin:$(date +%s)
