name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ｜
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/store_admin/xs-web-admin:$(date +%s)
        docker push registry.cn-shanghai.aliyuncs.com/store_admin/xs-web-admin:$(date +%s)
